### ISSUE TITLE
Lock and Key Dungeon Generation?

### ISSUE THREAD

**Issue by rdg922** [theshaggydev/the-shaggy-dev-projects#1]
I was really interested in the lock and key dungeon generation code you have and wanted to see a bit more of what is on your blog and in the video. I was curious if you still had the code and could upload to this repository. Thanks!

**Comment by theshaggydev** [comment]
Good suggestion! I needed to do some cleanup on it before making it public and had been lazy about doing that.

I just uploaded it to the repo [here](https://github.com/theshaggydev/the-shaggy-dev-projects/tree/main/projects/big-key-dungeon-generator) along with a few notes for usage. Hope this helps!

**Comment by rdg922** [comment]
Thank you so much!
